#+TITLE: Historique et évolution du projet OLPC/Saint-Ouen

* Contributeurs

- BG : Bastien Guerry
- MPC : Muriel Prévot-Carpentier
- SU : Sandrine Ubeda

* Historiques

- BG: Février 2016 : Sandra fait remonter une demande des élèves de
  pouvoir prendre leur ordinateur à domicile.

- MPC: 18 février 2016 : les élèves de CM2 ont fait cette demande à
  leur enseignante de manière informelle ("Madame ce serait trop bien
  de pouvoir emmener les XO pendant les vacances") pour pouvoir
  continuer de l'utiliser pendant les deux semaines d'absence de
  l'école pendant les vacances de février.

- BG: 7 avril 2016 : réunion avec Céline, Sandra, Manoya, Muriel,
  Lionel, Bastien (voir le [[https://olpc-france.org/wiki/index.php?title=Compte_rendu_reunion_saintouen_avril_2016][compte-rendu]])

- BG: 8 avril 2016 : remontée d'un bug par Muriel : dans TuxMath, le
  jeu Factoroide fonctionne mais au bout d’un moment assez court (1 à
  2 minutes) renvoie à la page d’accueil.

- BG: 12 avril : Retour de Sandrine sur l'écran qui se fige,
  validation possibilité de reflashage des machines fin août.

- BG: 13 avril : Lionel fait un retour sur le bug de lecture vidéo.

- BG: 10 mai : Céline envoie de nouveaux fichiers à mettre sur le serveur.

- BG: 12 mai : visite dans la classe et installation du serveur (voir [[https://olpc-france.org/blog/2016/05/olpc-france-installe-un-serveur-de-contenus-pour-lecole-de-saint-ouen/][blog]]) - correction bug clavier qwerty pour tuxmath.

- MPC. 1er juin 2016 : échange avec Bastien sur la visite du 12
  mai. Le bug tuxmath n'était pas technique, le clavier reste en
  QWERTY sur tuxmath, les élèves ont eu l'explication par Bastien.

- SU : Juin : Céline aurait la possibilité de travailler sur des
  tablettes dès la rentrée, ce qui éviterait de déplacer les XO et
  d'adapter l'expérimentation aux besoins de Céline.

* Questions

- Le serveur suivrait il Céline, ou le met on directement en ligne?
- Quelle sera l'avancée de sugarizer à la rentrée 2016?
- Qui serait intéressé par l'utilisation des XO sur Mandela et lancer une nouvelle expérience?
